### ISSUE TITLE
Bug EUTelDafFitter

### ISSUE THREAD

**Issue by TCThenna** [eutelescope/eutelescope#252]
- Hard coded collection name "fitpoints"

//Add track collection
  if(_addToLCIO)
  { 
    event->addCollection(_fittrackvec,_trackCollectionName); 
    std::string  sfitpoints = "" ;  

    
    for(int i = 0; i<1000; i++)
    {
      sfitpoints = "fitpoints" + i;
      try
      {
       dynamic_cast < LCCollectionVec * > ( event->getCollection( sfitpoints ) )  ;
      }
      catch(...)
      {
        break;
      } 
    }
    event->addCollection(_fitpointvec, sfitpoints );
  }

 -> Will first merge with new version by Havard before fixing (or maybe already fixed in Havards code)

**Comment by tbisanz** [comment]
Yes, don't know if that's a bug or just how it is - but the DAFFitter points have a hard-coded name. If that causes problems for you, just add an optional parameter with the default name "fitpoints", giving the user the possibility to change it, but I guess you know that and the issue is just a reminder.
