### ISSUE TITLE
auto_ptr is deprecated

### ISSUE THREAD

**Issue by simonspa** [eutelescope/eutelescope#272]
```
In file included from /ilcsoft/v01-17-05/Eutelescope/trunk/include/EUTelTrackerDataInterfacerImpl.h:33:0,
                 from /ilcsoft/eudaq/main/lib/plugins/USBpixConverterPlugin.cc:23:
/ilcsoft/v01-17-05/Eutelescope/trunk/include/EUTelTrackerDataInterfacerImpl.tcc: In constructor ‘eutelescope::EUTelTrackerDataInterfacerImpl<PixelType>::EUTelTrackerDataInterfacerImpl(IMPL::TrackerDataImpl*)’:
/ilcsoft/v01-17-05/Eutelescope/trunk/include/EUTelTrackerDataInterfacerImpl.tcc:18:8: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   std::auto_ptr<PixelType> pixel ( new PixelType );
```

**Comment by tbisanz** [comment]
I think you've checked out an old EUTel version - because this is definitely not the case. However, now that you brought to my attention that EUDAQ includes EUTel files - we should make sure our C++14 flags are synced. I've (for now!) introduced a make_unique in namespace std (I know, never do stuff like this :P) and this will not compile with -std=c++14. 

I'm not sure if define guards will be able to properly catch that, certainly not if we don't include them nicely in the project build files. Are there any plans of moving there pretty soon? I'll try to figure out a solution!
