### ISSUE TITLE
Units in EUTelAlignGBL (and EUTelescope)

### ISSUE THREAD

**Issue by edorossi** [eutelescope/eutelescope#394]
I noticed that all the cuts (and the plots) are set in um, while the standard units in EUTelescope and Gear is mm. Something similar happens in `EUTelMille`. Is there any good reason to use um, or should we pass to mm in every variable accessible by the user?

Moreover, I don't know how to behave with angles. In gear they are in degrees, in the plots in EUTelAlignGBL are in mrad and sometimes I had them in rad.  Is there a preferred unit in this case?

**Comment by TCThenna** [comment]
I opt for mm and mrad.

**Comment by tbisanz** [comment]
Consistency is important, so I'm totally for this. 

The only input I have: GEAR will stick to angles, we won't start changing this at this state. This will break all the old GEAR files. So I'd opt for `mm` and `deg`.

I'd also suggest every option description for every `Marlin` processor should indicate what unit it uses, even if they are consistent!

**Comment by jha92** [comment]
I think it would be good to include e.g. unit definition to the style guide for writing processors.
Another example, where one can unify is the ordering scheme for parameter vectors. I am not that experienced, but are there good region to switch definitions between ordered in z and ordered in ID?

**Comment by tbisanz** [comment]
Always use z-ordering! But yes, that should be documented somewhere!

The reason is that the way to retrieve the sensors is via `geo::gGeometry().sensorIDsVec()` which returns them z-ordered. The only other ways would be GEAR ordered, which the processor shouldn't know about (no processor should know about GEAR) and scending or descending in id - which is also kind of arbitrary.

**Comment by TCThenna** [comment]
For scattering related quantities, we usually deal with small angles, so mrad is very handy. Especially if we want cut values (triCut, triplet-driplet-matching, ...) to be easily estimated. I'd also like the plots in mrad. The Highland formula is radian. So we would have to convert the Highland input to GBL to degrees, which none of the users of this code is used to. 

Any ideas how to solve this nicely?

**Comment by tbisanz** [comment]
I don't have big problems with the GEAR file using degree and the rest mrad. Internally we definitely should use (m)rad!

**Comment by tbisanz** [comment]
So, anyone against using `mm` and `mrad`? If not, let's define that. What about plots? Should we stick to mm there as well?

**Comment by thomaseichhorn** [comment]
I would suggest to keep the input angles in gear in degrees, since this is mostly used to set a rotated DUT and users have a 'feeling' for degrees. Also the rotation precision is not always on the mrad level.
In plots and for scattering, as previously pointed out, quantities are small, so mrad should be used.

For input distances, mm is fine, but for output plots it can be a bit cumbersome to always convert mm to um to get a feeling for e.g. a sensor misalignment. On the other hand, a hitmap in um is also not ideal... I would therefore suggest to accept both um and mm, on the condition that it is explicitly specified everywhere (axis label or processor input description) which unit is used.

**Comment by edorossi** [comment]
Small question related to Thomas' message: is it fine if we leave the cut related plots (triplet matching distance and similar) in mm? Those plots are related to the input cuts (which are in mm) and this link can become less evident if the units are different.

**Comment by tbisanz** [comment]
Final decision: user parameters should be in *rad* and *mm* (despite this, indicate it in the parameter description). Histograms may use what suits them (with corresponding axis label) and GEAR will stay with degree. Closing.
